### ISSUE TITLE
`undefined is not a function`

### ISSUE THREAD

**Issue by NoodleOfDeath** [enesozturk/react-native-hold-menu#104]
**Describe the bug**
Pressing any action prompts an `undefined is not a function` error on line 3 of `MenuItem.tsx`

**To Reproduce**
1.  Add my `HoldMenuProvider` at the top of stack. 
2. Make a `HoldItem` component with `items={  [ { onPress: () => alert('wtf'), text:'what the actual fuck' }] }`
3. `yarn start --resetCache`
4. Open app. Click on the first item. Error happens

**Expected behavior**
An alert message that says `wtf`

**Actual behavior**
A runtime js error... will investigate to see if this is because react-native-reanimated is v3 instead of v2

**Screenshots**

![IMG_2454](https://github.com/enesozturk/react-native-hold-menu/assets/14790443/c6cd77cd-b233-47fb-a99a-796c0c9813ec)

**Package versions**
 - React: `18.2.0`
 - React Native: `^0.71.8`
 - React Native Reanimated: `^3.3.0`
 - React Native Hold Menu: `^0.1.6`
 - Expo: `^48.0.0`

**Additional context**

**Comment by NoodleOfDeath** [comment]
okay, seems like it was a react-native-renanimated issue. downgrading to 2.7.0 fixed this. will you make support for v3. my app kind of needs it

**Comment by ice-cap0** [comment]
yes please
