### ISSUE TITLE
Crash with latest version of reanimated2

### ISSUE THREAD

**Issue by zhigang1992** [enesozturk/react-native-hold-menu#17]
**Describe the bug**
Example app crashes with reanimated 2.0.1

**To Reproduce**
Upgrade to reanimated 2.0.1
Open example app

**Screenshots**
<img width="605" alt="image" src="https://user-images.githubusercontent.com/1057756/112785352-5cb03000-9086-11eb-900f-740a93e26ef4.png">

**Package versions**
See example app

**Comment by enesozturk** [comment]
Hi @zhigang1992, could your provide other details like code snippets? How did you implement it? I will try to reporduce it.

**Comment by zhigang1992** [comment]
I'm running the example app, with reanimated upgraded to 2.0.1

**Comment by ksitko** [comment]
This is what I had been seeing myself as per our previous discussion in #11 @enesozturk Perhaps it would be worth opening a new issue in the Reanimated repo?

**Comment by enesozturk** [comment]
> Yeah, it seems like it's not released
> 
> [software-mansion/react-native-reanimated#1874 (comment)](https://github.com/software-mansion/react-native-reanimated/issues/1874#issuecomment-809123683)

Oh this is good to know 😄 As I guessed [here](https://github.com/enesozturk/react-native-hold-menu/discussions/11#discussioncomment-533788) it is not included in v2.0.1 as I understood. Will wait the new release. But at the end, it is not good to force people to use latest version of Reanimated..

**Comment by enesozturk** [comment]
https://github.com/software-mansion/react-native-reanimated/releases/tag/2.1.0
It is here 🔥 Lets try guys 🤓

**Comment by BooYeu** [comment]
@enesozturk it is ok. Thank you very much!!! looking forwards to the function of switching from longPress to one click(onPress) able! ^_^

**Comment by BooYeu** [comment]
Your design is so beautiful! This is my favorite react native program ! Thank you very much!!!!!

**Comment by zhigang1992** [comment]
The crash is indeed fixed. 👍 

The example app is working as expected.

Quick question, do we need to save the whole onPress callback in shared value? Could it be on the context instead?

**Comment by enesozturk** [comment]
> The crash is indeed fixed. 👍 
> 
> 
> 
> The example app is working as expected.
> 
> 
> 
> Quick question, do we need to save the whole onPress callback in shared value? Could it be on the context instead?
> 
> 

That is great to know 👍🏽 Good question. It is important to move list data super fast because for example in Whatsapp, message sender and receiver hast different list values. That is why shared value is needed. It is already in context actually.
