### ISSUE TITLE
Can't change theme auto

### ISSUE THREAD

**Issue by BooYeu** [enesozturk/react-native-hold-menu#18]
**Describe the bug**
Can't change theme auto.

**To Reproduce**
have a button to change theme , the theme value changed but react-native-hold-menu's theme didn't change

**Expected behavior**
react-native-hold-menu's theme props change with its value

**Package versions**
 - React:17.0.2
 - React Native:0.64.0
 - React Native Reanimated:2.1.0
 - React Native Hold Menu:0.0.8
 - Expo: react-native-unimodules@0.13.0

**Additional context**
the demo code is below~~

```
const [flag,setFlag] = useState(false);
const theme = useMemo(()=>flag?'light':'dark',[flag]);

return (
<HoldMenuProvider theme={theme}>
<TouchableOpacity onPress={()=>setFlag(true)}>test</TouchableOpacity>
</HoldMenuProvider>
);
```

the HoldMenu theme doesn't change

**Comment by BooYeu** [comment]
`const [flag,setFlag] = useState(false);
const theme = useMemo(()=>flag?'light':'dark',[flag]);

return (
<HoldMenuProvider theme={theme}>
<TouchableOpacity onPress={()=>setFlag(true)}>test</TouchableOpacity>
</HoldMenuProvider>
);`

**Comment by enesozturk** [comment]
Hi @BooYeu, there was a little logic bug about this issue and probably will be fixed after https://github.com/enesozturk/react-native-hold-menu/pull/24. If not, you can reopen the issue. Thanks for let me know 🙌🏽
