### ISSUE TITLE
Can holdItem stop its children's onPress function when the holdItem is active(open)?

### ISSUE THREAD

**Issue by BooYeu** [enesozturk/react-native-hold-menu#19]
**Describe the bug**

**To Reproduce**
HoldItem has a TouchableOpacity

**Expected behavior**
Can holdItem stop its children's onPress(any touch function) function when the holdItem is active(open)?

**Actual behavior**
A clear and concise description of what happened.

**Screenshots**
-

**Package versions**
 - React:17.0.2
 - React Native:0.64.0
 - React Native Reanimated:2.1.0
 - React Native Hold Menu:0.0.8
 - Expo: react-native-unimodules

**Additional context**
none

**Comment by enesozturk** [comment]
Hi @BooYeu. Thanks for your feedback and that would be very useful 🙌🏽 
I added this to my todo list and will consider for new releases. Closing issue for now.
