### ISSUE TITLE
Ability to use without blur view and with taps instead of long presses

### ISSUE THREAD

**Issue by jackspiva** [enesozturk/react-native-hold-menu#2]
Hi! Thanks so much for the awesome library! 

I was wondering if you'd be open to supporting use of this package as more of a general purpose context menu? I'd like to use it to open a context menu on tap (instead of on long press), and without a blurred background. I'm thinking something like https://github.com/instea/react-native-popup-menu, but with the awesome animation and smoothness of this package. 

I forked and quickly updated it to work that way, and would be happy to open a PR eventually, but wasn't sure if that fit your vision for the package.

**Comment by enesozturk** [comment]
Hi Jack 👋🏽 Thank you so much, I am glad yo here these.

It is exactly great feedback that I thought similar before but did not implemented yet.

Any prop for activate behaviour like 'activateOn="tap|double-tap|hold"' would be awesome! I will add that to my to do list ✅

**Comment by markmccoid** [comment]
This might be a similar request, but I would like to be able to have a default action taken on a press. Just like it was wrapped with TouchableOpacity and then Long Press would show the menu.

My scenario is a main screen with a list of movie poster images that when pressed send the user to a details page.  But I would like to use this to pop open an action menu on long-press to let users delete and do some other simple actions.

I've done some testing and can't figure out how to get this behavior.

Other than that this library looks beautiful and I thank you so much for sharing it with us!

**Comment by enesozturk** [comment]
Hİ @markmccoid, as I understood in your scenario you want to implement such an example; 

Call any action onPress and open menu on long press, here is video what I did including the code and result. Is this the what your are asking for?

https://user-images.githubusercontent.com/19428358/110230160-1e5ca080-7f20-11eb-86da-f0b41a021550.mov

**Comment by markmccoid** [comment]
Yes, but am still trying to figure out a way to make sure once Hold Menu is activated, that the Press action is disabled.

**Comment by enesozturk** [comment]
> Yes, but am still trying to figure out a way to make sure once Hold Menu is activated, that the Press action is disabled.

I added this to improvement todo list ([see](https://github.com/enesozturk/react-native-hold-menu/projects/1#card-56458482)) and will consider for the next release. Tap option feature is merged thanks to @ksitko. Optional backdrop is in my to do list as well.  [See](https://github.com/enesozturk/react-native-hold-menu/projects/1#card-55743583)

Closing issue, thanks guys 👊🏽

**Comment by nathan-fiscaletti** [comment]
This doesn't really address the concern of being able to disable the "blur" background when it's tapped. Sometimes I just want the context menu to come up but i don't want the background to be blurred.

**Comment by pugson** [comment]
+1 for disabling blur. If you have your own Expo `BlurView` anywhere it throws an error:
`Tried to register two views with the same name ViewManagerAdapter_ExpoBlurView`

**Comment by stevewillard** [comment]
@pugson did you find a solution for not blurring the background? I'm interested in the same behavior

**Comment by pugson** [comment]
@stevewillard yeah using another library: https://zeego.dev / https://github.com/nandorojo/zeego
