### ISSUE TITLE
ios not working 

### ISSUE THREAD

**Issue by Turkialmalki** [enesozturk/react-native-hold-menu#20]
**Describe the bug**
null is not an object (evaluating 'NativeUnimoduleProxy.viewManagersNames')

<img width="562" alt="Screen Shot 1442-09-07 at 2 06 04 PM" src="https://user-images.githubusercontent.com/46572668/115226864-632b4800-a118-11eb-903f-0ada58b0da33.png">

**Package versions**
 - React: 16.13.1
 - React Native: 0.63.3
 - React Native Reanimated: 2.0.0
 - React Native Hold Menu: 0.0.8
 - Expo: I don’t use expo in my project

**Comment by ksitko** [comment]
Update to `"react-native-reanimated": "2.1.0"`

**Comment by enesozturk** [comment]
Hi @Turkialmalki, sorry for being late. Is the issue solved by upgrading Reanimated? Looks like it is related with Expo Unimodules. If it is not solved. Try installing again [unimodules](https://docs.expo.io/bare/installing-unimodules/)

**Comment by ilyasbat** [comment]
same issue
react-rative-reanimated version is 2.1.0 
react-native-unimodules version is  0.13.3 and react-native-gesture-handler is 1.10.3.
I deleted node_modules and install again but i still get error.

**Comment by enesozturk** [comment]
Hi @ilyasbat, did you followed the installation steps of unimodules [here](https://docs.expo.io/bare/installing-unimodules/). I am trying to understand and reproduce the problem.

**Comment by Turkialmalki** [comment]
> Update to `"react-native-reanimated": "2.1.0"`

@ksitko Still same issue

**Comment by Turkialmalki** [comment]
> Hi @Turkialmalki, sorry for being late. Is the issue solved by upgrading Reanimated? Looks like it is related with Expo Unimodules. If it is not solved. Try installing again [unimodules](https://docs.expo.io/bare/installing-unimodules/)

@enesozturk The issue still the same, even after upgrading Reanimated

**Comment by enesozturk** [comment]
Hi, looks like there is no action for long time. The issue looks like related to Unimodules setup. Package versions are same with example project and can not reproduce the problem. For the future visitors, it would be good to check [unimodules setup](https://docs.expo.dev/bare/installing-unimodules/) again. Thanks!
