### ISSUE TITLE
don't run on androids  , Require cycle

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [enesozturk/react-native-hold-menu#35]
```
Require cycle: node_modules\react-native-hold-menu\src\components\provider\Provider.tsx -> node_modules\react-native-hold-menu\src\components\menu\index.ts -> node_modules\react-native-hold-menu\src\components\menu\Menu.tsx -> node_modules\react-native-hold-menu\src\components\menu\MenuList.tsx -> node_modules\react-native-hold-menu\src\components\menu\MenuItems.tsx -> node_modules\react-native-hold-menu\src\components\menu\MenuItem.tsx -> node_modules\react-native-hold-menu\src\components\provider\Provider.tsx

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
```
**Package versions**
 - React:17.0.0
 - React Native:0.64.1
 - React Native Reanimated:v2
 - React Native Hold Menu:
 - Expo: 

**Additional context**

**Comment by enesozturk** [comment]
Hi @liuhuapiaoyuan, I have never got this error in different example projects. Could you please share your workflow to use Hold Menu with code snippets?

**Comment by enesozturk** [comment]
I got the warning now. The reason it show this recycle is I import AnimatedIcon component from Provider file. This can be ignored. No idea how to refactor that Dynamic Icon structure but will try to improve to get rid of this message. Closing for now. Thanks!
