### ISSUE TITLE
Crash on startup when iconComponent is not provided to HoldMenuProvider

### ISSUE THREAD

**Issue by Pyroboomka** [enesozturk/react-native-hold-menu#36]
**Describe the bug**
Crash on application start if iconComponent is not provided to HoldMenuProvider with "cannot read property displayName of undefined"

**To Reproduce**
Clean install, follow the docs, assume that iconComponent is not needed if you don't want to use icons.

**Package versions**
 - React: 17.0.1
 - React Native: 0.64.2
 - React Native Reanimated: 2.2.0
 - React Native Hold Menu: 0.0.1

**Additional context**
Probably should add a default value of class component that renders null to HoldMenuProvider or/and mention it in the docs, since it's marked as required in Typescript defs.

**Comment by enesozturk** [comment]
Hi @Pyroboomka, icon component is not optional for now. I did not tried without icon actually but it make sense. Would be good to make it optional. Thanks!

**Comment by robertherber** [comment]
I don't think this is a problem per se - but it'd be great if it's specified in the docs and TypesScript! 🙂

**Comment by enesozturk** [comment]
This should be fixed by the new release. Changes were made in the last PR (https://github.com/enesozturk/react-native-hold-menu/pull/73). I'll publish it soon. Thanks!
