### ISSUE TITLE
Hold menu appears off screen on horizontal ScrollViews

### ISSUE THREAD

**Issue by 10000multiplier** [enesozturk/react-native-hold-menu#41]
**Describe the bug**
Hold menu appears off screen when nested inside a horizontal scrollview.

**Expected behavior**
Hold menu appears in screen.

**Actual behavior**
Hold menu appears partially off screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/57633368/129069586-ae02e39d-a06e-4e80-8bc9-6de69a43c73e.png)

**Package versions**
 - React: 16.13.1
 - React Native: 0.63
 - React Native Reanimated: 2.2.0
 - React Native Hold Menu: ^0.1.1
 - Expo: 42.0.0

**Comment by enesozturk** [comment]
Hi @10000multiplier, It is been a long time. There might be different reasons for this. Share some code snippets about your usage to let me check.

**Comment by enesozturk** [comment]
This issue is not active for a long time. Closing for now. Feel free to reopen if you have it again.
