### ISSUE TITLE
react-native-unimodules is deprecated

### ISSUE THREAD

**Issue by hirbod** [enesozturk/react-native-hold-menu#53]
The usage of react-native-unimodules is deprecated since Expo SDK 43. 
https://docs.expo.dev/bare/installing-unimodules/

Please consider to migrate to Expo Modules
https://docs.expo.dev/bare/installing-expo-modules/

**Comment by jay-jlm** [comment]
Can we have an update on the status?

**Comment by tomgreco** [comment]
@enesozturk @gorhom  can we please get this updated? Seems like a not so heavy lift.

**Comment by enesozturk** [comment]
Hi, thanks for letting us know, this is already done in https://github.com/enesozturk/react-native-hold-menu/pull/57. Did not released a new version yet but will do it soon. 🤞🏽

**Comment by Flam3rboy** [comment]
@enesozturk did you publish the new version yet?

**Comment by enesozturk** [comment]
The new version is released, thanks!

**Comment by ice-cap0** [comment]
docs still mention this
![Screenshot 2024-10-21 at 11 19 40 AM](https://github.com/user-attachments/assets/5afe56a2-ea56-45e0-b5bd-093cbc5441f1)
