### ISSUE TITLE
Performance problem in Android 

### ISSUE THREAD

**Issue by ameer-taghavi** [enesozturk/react-native-hold-menu#60]
Thanks for this amazing package. I used in my app but has not good performance in android. In iOS everything is good and smooth. But in android is so laggy!

**Comment by Flam3rboy** [comment]
Turn of "Debug JS in Browser", then everything will work fine on android.
This is related to the react-native-reanimated library, which is slow when remote debugging is turned on.

**Comment by ameer-taghavi** [comment]
> Turn of "Debug JS in Browser", then everything will work fine on android.
> This is related to the react-native-reanimated library, which is slow when remote debugging is turned on.

I had tested in production mode!

**Comment by ameer-taghavi** [comment]
@enesozturk can you help me?

**Comment by enesozturk** [comment]
Hi @ameer-taghavi, totally aware of that. iOS and Android have different limitations and performances. Many UI things do not give the same experience with iOS. I may need to do additional improvements for Android but I probably will be slow to make it. Also, this package may not be for the production apps yet. Sorry to can't help for now. Adding this to my to-do, closing the issue right now. Thanks for your interest!
