### ISSUE TITLE
Menu item colors are not reset between theme changes

### ISSUE THREAD

**Issue by jamesholcomb** [enesozturk/react-native-hold-menu#61]
**Describe the bug**
Menu item colors are not reset between dark and light theme changes

**To Reproduce**
```sh
git clone https://github.com/enesozturk/react-native-hold-menu
cd react-native-hold-menu
yarn
cd example
yarn
cd ios
npx pod-install
cd ..
yarn run ios
```

Note: I had to comment out flipper in the Podfile to get the app to build in xcode

See video recorded from the repo example app

**Expected behavior**
Theme colors should be preserved between toggle

**Actual behavior**
Menu item text and icon colors are not reset between theme changes

**Screenshots**
https://user-images.githubusercontent.com/362729/155426227-727e2f0a-52fa-4b84-afcb-988941186e40.mp4

**Package versions**
See example/package.json

**Additional context**

**Comment by enesozturk** [comment]
Hi @jamesholcomb, thanks for the detailed issue. I am already aware of this issue for a long time but no solution until now, unfortunately. Looks like I need to make some deep checks.

**Comment by enesozturk** [comment]
This should be fixed by the new release. Changes were made in the last PR (https://github.com/enesozturk/react-native-hold-menu/pull/73). Thanks!
