### ISSUE TITLE
Link to React Native Reanimated is dead

### ISSUE THREAD

**Issue by Myzel394** [enesozturk/react-native-hold-menu#63]
https://enesozturk.github.io/react-native-hold-menu/docs

"React Native Reanimated v2 needs extra steps to finalize its installation, please follow their installation instructions." <- Link is dead

New suggested link: https://docs.expo.dev/versions/latest/sdk/reanimated/

**Comment by enesozturk** [comment]
Done in [9fbde80](https://github.com/enesozturk/react-native-hold-menu/commit/9fbde80a26c1473336bf007f8500b9ddd6ba9754), thanks!
