### ISSUE TITLE
type error HoldItem onpress prop

### ISSUE THREAD

**Issue by dancixx** [enesozturk/react-native-hold-menu#65]
There is a type error If I use the actionParams with multiple args.

```
Type '(status: string, id: string) => void' is not assignable to type '(arg?: string | number | undefined) => void'.
```

The original type of `onPress?: (arg?: string | number) => void;`
Maybe this can be a solution for it: `onPress?: (...args: (string | number)[]) => void;`

**Comment by enesozturk** [comment]
Hi @dancixx, thanks for pointing out that! Also, it can be any other type but string or number. I updated in [#9fbde8](https://github.com/enesozturk/react-native-hold-menu/commit/9fbde80a26c1473336bf007f8500b9ddd6ba9754)!

**Comment by dancixx** [comment]
Thanks for fast reaction, but I think the any type can cause a worklet error. I looked a bit deeper into the source code and I saw you use reanimated worklet feature. When I passed a nested object as a param I got worklet error. I will check it again in next days and write the result.

**Comment by enesozturk** [comment]
Oh, good catch. Not a fan of `any` but didn't now that issue. Would be very happy!

**Comment by dancixx** [comment]
Ok, I have checked it. So the problem is coming when I try to pass a redux element and it is a frozen object because of that need a deep copy.
Here talk about this problem: https://github.com/software-mansion/react-native-reanimated/issues/1517#issuecomment-1078782556
Maybe you can write a little note in the docs because the redux-toolkit is a must-have package in RN projects the it is use `immer` under the hood which creates a frozen object.

**Comment by dancixx** [comment]
@enesozturk other thing, I can see the type update in the src/comp.../types.d.ts but in the lib folder the type is the original, do you have any idea, why?
