### ISSUE TITLE
Support preview view( like reaction...) like message,...

### ISSUE THREAD

**Issue by fukemy** [enesozturk/react-native-hold-menu#68]
Hi, sorry for wrong tag, im using mobile but i can not create a feature request.
As u can see the picture here, did u support to show a custom preview include reaction? Thanks

![image](https://user-images.githubusercontent.com/8202437/170690068-be804c0e-3eee-40c7-921d-d47dbb5e1361.png)

![image](https://user-images.githubusercontent.com/8202437/170690121-28141e45-d1a8-46ad-8817-24e67ebcb585.png)

**Comment by enesozturk** [comment]
Hi @fukemy. I'm already working on a feature called 'Preview' which is different than the reactions and also thinking about the reactions feature too! They are both [in my todos](https://github.com/enesozturk/react-native-hold-menu/projects/1#card-84340739). Thanks for the suggestion. I'm closing this for now.

**Comment by fukemy** [comment]
thanks you, as you can see telegram and rn stream chat can do it, i read the code of rn stream chat, it's writen preview using 100% reanimated.

**Comment by fukemy** [comment]
Hi bro, did u support this now? I really hope it's done soon

**Comment by fukemy** [comment]
Hi there, any update now?, I still waiting for u

**Comment by FlawaCLV** [comment]
I'm interested too in the feature. If you need any help on implementing it, I may have some time in the next weeks.

**Comment by fukemy** [comment]
@FlawaCLV Yes, I will wait for @enesozturk  update, could you please help? Thanks u so much
