### ISSUE TITLE
Menu displays behind modal screen

### ISSUE THREAD

**Issue by Joehoel** [enesozturk/react-native-hold-menu#80]
**Describe the bug**
When `HoldMenuItem` is used in a screen that has `presentation: 'modal'`. The hold-items display behind the modal instead of on top.

**Expected behavior**
The blur and menu items should be displayed on top of the modal view.

**Actual behavior**
The blur and menu items are displayed behind the modal view.

**Screenshots**
<img src="https://user-images.githubusercontent.com/31251240/187929429-6d14d93d-4fba-4d26-b787-c9a2149b8784.jpg" width=40% height=40%>

<img src="https://user-images.githubusercontent.com/31251240/187929483-3bc6c0a6-fffb-44fa-aa46-e58e29389ceb.jpg" width=40% height=40%>

**Package versions**
 - React: 18.0.0
 - React Native: 0.69.5
 - React Native Reanimated: 2.9.1
 - React Native Hold Menu: 0.1.5
 - Expo: 46.0.0

**Comment by franznkemaka** [comment]
Hi @Joehoel, 

I just had the same issue, the temporal workaround until this is fixed is to add the `HoldMenuProvider` inside the screen with `presentation: 'modal'`.  Because it will be relative to that and show inside the page
