### ISSUE TITLE
Position of element doesn't take header and other content into account

### ISSUE THREAD

**Issue by kesha-antonov** [enesozturk/react-native-hold-menu#83]
**Describe the bug**
Hi
As in title:

<img width="446" alt="Screenshot 2022-11-11 at 16 20 07" src="https://user-images.githubusercontent.com/11584712/201348753-cc94a503-0e3a-4093-881a-5cc94e9c32e1.png">

<img width="453" alt="Screenshot 2022-11-11 at 16 17 20" src="https://user-images.githubusercontent.com/11584712/201348679-c6bd55e3-580d-4d95-a948-e604f73cc2d1.png">

The popup positioned lower than it should. If I remove header and text content then position is correct. I think the lib measures absolute position, not relative

 - React: 18.1.0
 - React Native: 0.70.5
 - React Native Reanimated: ^2.12.0
 - React Native Hold Menu: enesozturk/react-native-hold-menu#83cc6f76ac49828ecf94391138820cc0b9be433e
 - Expo: ^47.0.3

**Comment by enesozturk** [comment]
Hey @kesha-antonov, not sure still using this lib, I'd like to ask if the `HoldMenuProvider` is **outside** of the NavigationContainer. If not, it's expected to see this. Otherwise it should be ok.
