### ISSUE TITLE
Error: Unable to resolve module @unimodules/core

### ISSUE THREAD

**Issue by productfrontenddeveloper** [enesozturk/react-native-hold-menu#9]
**Describe the bug**
```
> 1 | import { NativeModulesProxy, requireNativeViewManager } from '@unimodules/core';
    |                                                               ^
  2 | import * as React from 'react';
  3 | import { findNodeHandle, View, StyleSheet } from 'react-native';
  4 | export default class BlurView extends React.Component {]
``` 

1. yarn add react-native-hold-menu
2. ```import { HoldItem } from 'react-native-hold-menu';``` 
3. used ```<HoldItem items={MenuItems}>... </HoldItem>
4. yarn start 
5. See error

**Screenshots**
<img width="595" alt="Screen Shot 2021-03-09 at 17 24 03" src="https://user-images.githubusercontent.com/38668796/110484999-40127f00-80fc-11eb-8b6b-d01ddd253d41.png">

**Package versions**
 - React: 17.0.1
 - React Native: 0.64.0-rc.4
 - React Native Reanimated: 2.0.0

**Comment by enesozturk** [comment]
Hi @productfrontenddeveloper, Hold menu is using Expo modules for Blur view (expo-blur) and will use expo-haptic soon. That is why **react-native-unimodules** instructions must be done and this is missing in documentation. Thanks for feedback. Following [this steps](https://github.com/expo/expo/tree/master/packages/react-native-unimodules) must solve the issue.

**Comment by productfrontenddeveloper** [comment]
Thanks for the return, Can you give a date for the expo-haptic ?

**Comment by enesozturk** [comment]
It is merged already (https://github.com/enesozturk/react-native-hold-menu/pull/5) and I will create new release in several days. Let me know unimodules installation solves your issue.

**Comment by productfrontenddeveloper** [comment]
Actually I don't want to install and deal with the settings, but I'll try it for you. (unimodules). soon

**Comment by enesozturk** [comment]
That is ok then. Closing issue for now and you can reopen it if the installation won't work for you 👍🏽

**Comment by productfrontenddeveloper** [comment]
```"react-native-hold-menu": "https://github.com/enesozturk/react-native-hold-menu",``` 
I said let me test my new version, some problem,
Are unimodules mandatory ?

**Comment by enesozturk** [comment]
Yes _unimodules_ is mandatory because backdrop and menu background uses **expo-blur**.

Expo haptic is not a pressable component. It is for vibration.

**Comment by productfrontenddeveloper** [comment]
> Hi @productfrontenddeveloper, Hold menu is using Expo modules for Blur view (expo-blur) and will use expo-haptic soon. That is why **react-native-unimodules** instructions must be done and this is missing in documentation. Thanks for feedback. Following [this steps](https://github.com/expo/expo/tree/master/packages/react-native-unimodules) must solve the issue.


<img width="628" alt="Screen Shot 2021-03-09 at 19 42 08" src="https://user-images.githubusercontent.com/38668796/110505790-89b89500-810f-11eb-8971-0e87736e6ec1.png">

**Comment by productfrontenddeveloper** [comment]
<img width="628" alt="Screen Shot 2021-03-09 at 20 07 30" src="https://user-images.githubusercontent.com/38668796/110509420-23357600-8113-11eb-9149-b5f863e0e0c9.png">


![Screen Shot 2021-03-09 at 20 08 58](https://user-images.githubusercontent.com/38668796/110509566-49f3ac80-8113-11eb-83b9-54de66e56135.png)
