### ISSUE TITLE
Is project still maintained ?

### ISSUE THREAD

**Issue by n0mer** [enesozturk/react-native-hold-menu#97]
Hi @enesozturk , congratulations with your new job and Center Pixel and relocation to USA.

What do you think of transfering this repo to one of fork authors? 

Project is still used, but forks can help only with one-time temp fixes that ultimately should land in main repository:

<img width="356" alt="image" src="https://user-images.githubusercontent.com/1862997/229774857-94645c9c-54e7-45ec-859e-a1716b3dd3af.png">

@athombv @SohelIslamImran what do you think, is there oss maintainer with good reputation to take over or a least merge PRs with fixes and keep dependencies (expo. haptics etc) up-to-date ? Expo has 6 month compatibility window, so this should be done on a regular basis.

**Comment by SohelIslamImran** [comment]
That would be great.

**Comment by n0mer** [comment]
Can you publish your fork under different npm coordinates , post link there - so people can add pull requests from their fork to that new repo ? Until @enesozturk is back, we would have consolidated version with fixes. For example , fork of @athombv (which is most fresh) is missing zIndex fix that is present in other fork .

**Comment by enesozturk** [comment]
Hey @n0mer. Thank you for considering the state of this package. I don't think about moving this package to another author. It's been a while since I couldn't take care of the issues & PRs, and I am still not pretty sure that this production-ready package is. Running this animation on low-end devices might lead to a bad user experience. I am open to PRs that improve the user experience especially low-end & Android devices.

Let me check out the recent PRs and merge them if they are ok. Thanks, have a great day.

**Comment by n0mer** [comment]
@enesozturk can you please re-consider #76 and corresponding contribution from #77 by @SohelIslamImran SohelIslamImran

**Comment by kesha-antonov** [comment]
> Hey @n0mer. Thank you for considering the state of this package. I don't think about moving this package to another author. It's been a while since I couldn't take care of the issues & PRs, and I am still not pretty sure that this production-ready package is. Running this animation on low-end devices might lead to a bad user experience. I am open to PRs that improve the user experience especially low-end & Android devices.
> 
> Let me check out the recent PRs and merge them if they are ok. Thanks, have a great day.

Hi
We use it in production for a while and it works good
rn-reanimated and rn-gesture-handler libs on which this package is based proved that they're fast and stable
So it would be great to see this package have maintenance
